// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {}; loadServices();

module.exports = {
  // An array of folders (excluding subfolders) where your tests are located;
  // if this is not specified, the test source must be passed as the second argument to the test runner.
  src_folders: ['tests'],
  output_folder : "./reports",

  // See https://nightwatchjs.org/guide/working-with-page-objects/
  page_objects_path: ['page-objects'],

  // See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-commands
  custom_commands_path:  ['custom-commands'],

  // See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-assertions
  custom_assertions_path: ['custom-assertions'],

  // See https://nightwatchjs.org/guide/#external-globals
  globals_path : 'globalsModule.js',

  webdriver: {},

  test_settings: {
    default: {
      disable_error_log: false,
      launch_url: 'https://suitsupply.com/en-fi/home',

      screenshots: {
        enabled: false,
        path: 'screens',
        on_failure: true
      },

      desiredCapabilities: {
        browserName : 'chrome',
        acceptSslCerts: true,
        chromeOptions : {
          args: [
            '--ignore-certificate-errors'
          ]
        }
      },

      webdriver: {
        start_process: true,
        port: 9515,
        server_path: (Services.chromedriver ? Services.chromedriver.path : ''),
        cli_args: [
          // --verbose
        ]
      }
    },

    'testing': {
      launch_url: 'https://storefront:alpaca2020@testing.suitsupply.com/en-fi/home',
    },
    
    'staging': {
      launch_url: 'https://storefront:alpaca2020@acceptance.suitsupply.com/en-fi/home'
    }
  }
};

function loadServices() {
  try {
    Services.seleniumServer = require('selenium-server');
  } catch (err) {}

  try {
    Services.chromedriver = require('chromedriver');
  } catch (err) {}

  try {
    Services.geckodriver = require('geckodriver');
  } catch (err) {}
}
